module Maths.NumberTheory.Primes
( primes
) where

-- list of prime numbers generated by the Sieve of Eratosthenes
primes :: [Int]
primes = sieve $ 2:[3,5..]
         where sieve (p:ns) = p : sieve [n | n <- ns, n `mod` p /= 0]
